### PR TITLE
xchacha: refactor to remove dead code

### PR DESCRIPTION
**Pull request by ncruces**
I dunno how you'll feel about this one, as you said you (understandably) didn't want to meddle with the original package too much.

This removes Andreas' (vendored) implementation of HChaCha20, since `x/crypto` provides a suitable one.

It doesn't cause any difference at all... because Adiantum doesn't use this _at all_ (see this [coverage report](https://gist.githack.com/ncruces/f0d7eb7432a5854271be4e5b7b5eee17/raw/bd5339409cce0ea779e3189264efbc55a7bcce2d/adiantum-coverage.html#file3)). It uses HChaChaN (with configurable rounds) in other places instead.

I guess merging `chacha` into `xchacha` would drop even more code.
Not sure what would make it easier to maintain, though.

So feel free to close. The point is **not** to give you any more headaches, is to figure out if there's anything to make this _less_ of a burden.

PS: thanks for the tag!

### CODE REVIEW

**Comment by lukechampine** [comment]
hmm. I've reconsidered -- let's custom tailor `internal/chacha` and `internal/xchacha` to the needs of Adiantum. We can probably even combine them into one package. It feels silly to retain dead code; as long as we remove it thoughtfully, I don't think there's any real reason for concern.

**Comment by ncruces** [comment]
OK, I get something for you to review.
Thanks!

**Comment by ncruces** [comment]
This should already give you an idea of the amount of code that can be removed.
But ISTM the `xchacha.go` file can be merged with `chacha.go`.

**Comment by lukechampine** [comment]
nice. Yes, I agree, we can merge `xchacha.go` and `chacha.go`. Also, the package should be named `xchacha`, not `chacha`.

**Comment by ncruces** [comment]
OK. I chose the name just so the diffs were easier to follow (helps me have more confidence in what I'm doing), but I'll do a final rename before opening up for review.

I may also try to factor the generic ChaCha round-pair, as we cary two implementations of it.

**Comment by ncruces** [comment]
I think this is ready for review. I'd probably squash this one and tweak the commit message, as I don't think the intermediate commits add much value.

Only the `chacha_test.go` diff doesn't carry over.

I kept the two ChaCha implementations, as the loop is too big to inline.

**Comment by lukechampine** [comment]
rad

**Comment by ncruces** [comment]
Would it make sense to tag this? I'm not planning any more contributions.

(I have an hacked up version of [s390x](https://github.com/ncruces/adiantum/tree/s390x) assembly - based on `x/crypto` - but I don't think it's very mergeable; almost no one will use it, why maintain it?)

**Comment by lukechampine** [comment]
tagged! thanks for your help. :) I agree, not much need for s390x

**Pull request merged**
